### ISSUE TITLE
Incompatable ReadMe with respect to MakeFile

### ISSUE THREAD

**Issue by mohammed1916** [merledu/OpenTcam#17]
The following commands need to be updated:
apidocs → gen_apidocs (also in workflow yaml file)
rununittest → run_unittest
runregression → run_regression
coverage  → run_coverage
cleanall → clean_all

**Comment by mohammed1916** [comment]
Also
To make compatable with MakeFile:
`make opentcam_venv` has been corrected to `make venv_opentcam` in this pull request: https://github.com/merledu/OpenTCAM/pull/16

**Comment by zeeshanrafique23** [comment]
Thanks for your contribution, picked and merged.
